[project]
src = "src"
out = "out"
dot_env = ".env"
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["snekmate"]

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
default_account_name = "anvil1"

[networks.era_test_node]
url = "http://127.0.0.1:8011"
is_zksync = true
prompt_live = false
default_account_name = "zk-rich1"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
